# Another Method - being used by ../Makefile
# vpath %.h ../include
# fibo : main.c fibo.c fibo.h
# 		gcc -c -o main.o main.c -I "../include/"
# 		gcc -c -o fibo.o fibo.c -I "../include/"
# clean :
# 		rm *.o
